CREATE TABLE WORKOUTS (
    WORKOUT_ID UUID DEFAULT GEN_RANDOM_UUID(),
    WORKOUT_NAME TEXT NOT NULL DEFAULT format(''),
    WORKOUT_DESCRIPTION TEXT NULL,
    USER_ID UUID REFERENCES USERS ON DELETE CASCADE,
    PRIMARY KEY (WORKOUT_ID)
);

ALTER TABLE
    WORKOUTS ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can create workouts" ON WORKOUTS FOR ALL TO AUTHENTICATED USING (
    (
        SELECT
            AUTH.UID()
    ) = USER_ID
) WITH CHECK (
    (
        SELECT
            AUTH.UID()
    ) = USER_ID
);