CREATE TABLE TEMPLATES (
    TEMPLATE_ID UUID DEFAULT GEN_RANDOM_UUID(),
    TEMPLATE_NAME TEXT NULL,
    TEMPLATE_DESCRIPTION TEXT NULL,
    USER_ID UUID REFERENCES USERS ON DELETE CASCADE,
    PRIMARY KEY (TEMPLATE_ID)
);
ALTER TABLE TEMPLATES ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can create templates" ON SESSIONS FOR ALL TO AUTHENTICATED 